hmr:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint1_position_controller:
    type: position_controller/JointPositionController
    joint: ljoint1
  joint2_position_controller:
    type: position_controller/JointPositionController
    joint: ljoint2
  joint1_position_controller:
    type: position_controller/JointPositionController
    joint: ljoint3
  joint2_position_controller:
    type: position_controller/JointPositionController
    joint: rjoint1
  joint1_position_controller:
    type: position_controller/JointPositionController
    joint: rjoint2
  joint2_position_controller:
    type: position_controller/JointPositionController
    joint: rjoint3        