hmr_controller:
  # Publish all joint states -----------------------------------
  type: "effort_controllers/JointTrajectoryController"
  joints:
    - ljoint1
    - ljoint2
    - ljoint3
    - rjoint1
    - rjoint2
    - rjoint3
  # Position Controllers ---------------------------------------
  gains: 
    ljoint1: {p: 100, i: 1, d: 1}
    ljoint2: {p: 100, i: 1, d: 1}
    ljoint3: {p: 100, i: 1, d: 1}
    rjoint1: {p: 100, i: 1, d: 1}
    rjoint2: {p: 100, i: 1, d: 1}
    rjoint3: {p: 100, i: 1, d: 1}